<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Albums', 'doctrine');

/**
 * BaseAlbums
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $aid
 * @property timestamp $created
 * @property timestamp $mod
 * @property integer $cover_pid
 * @property string $name
 * @property string $description
 * @property integer $sort_order
 * 
 * @method integer   getAid()         Returns the current record's "aid" value
 * @method timestamp getCreated()     Returns the current record's "created" value
 * @method timestamp getMod()         Returns the current record's "mod" value
 * @method integer   getCoverPid()    Returns the current record's "cover_pid" value
 * @method string    getName()        Returns the current record's "name" value
 * @method string    getDescription() Returns the current record's "description" value
 * @method integer   getSortOrder()   Returns the current record's "sort_order" value
 * @method Albums    setAid()         Sets the current record's "aid" value
 * @method Albums    setCreated()     Sets the current record's "created" value
 * @method Albums    setMod()         Sets the current record's "mod" value
 * @method Albums    setCoverPid()    Sets the current record's "cover_pid" value
 * @method Albums    setName()        Sets the current record's "name" value
 * @method Albums    setDescription() Sets the current record's "description" value
 * @method Albums    setSortOrder()   Sets the current record's "sort_order" value
 * 
 * @package    pd
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAlbums extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('albums');
        $this->hasColumn('aid', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('created', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('mod', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('cover_pid', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('sort_order', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}