<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Photos', 'doctrine');

/**
 * BasePhotos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $pid
 * @property timestamp $created
 * @property timestamp $mod
 * @property string $caption
 * @property string $file
 * @property integer $aid
 * @property integer $sort_order
 * 
 * @method integer   getPid()        Returns the current record's "pid" value
 * @method timestamp getCreated()    Returns the current record's "created" value
 * @method timestamp getMod()        Returns the current record's "mod" value
 * @method string    getCaption()    Returns the current record's "caption" value
 * @method string    getFile()       Returns the current record's "file" value
 * @method integer   getAid()        Returns the current record's "aid" value
 * @method integer   getSortOrder()  Returns the current record's "sort_order" value
 * @method Photos    setPid()        Sets the current record's "pid" value
 * @method Photos    setCreated()    Sets the current record's "created" value
 * @method Photos    setMod()        Sets the current record's "mod" value
 * @method Photos    setCaption()    Sets the current record's "caption" value
 * @method Photos    setFile()       Sets the current record's "file" value
 * @method Photos    setAid()        Sets the current record's "aid" value
 * @method Photos    setSortOrder()  Sets the current record's "sort_order" value
 * 
 * @package    pd
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePhotos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('photos');
        $this->hasColumn('pid', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('created', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('mod', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('caption', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('file', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('aid', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('sort_order', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}