<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Comments', 'doctrine');

/**
 * BaseComments
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cid
 * @property integer $pid
 * @property timestamp $created
 * @property string $subject_name
 * @property string $subject_id
 * @property string $text
 * 
 * @method integer   getCid()          Returns the current record's "cid" value
 * @method integer   getPid()          Returns the current record's "pid" value
 * @method timestamp getCreated()      Returns the current record's "created" value
 * @method string    getSubjectName()  Returns the current record's "subject_name" value
 * @method string    getSubjectId()    Returns the current record's "subject_id" value
 * @method string    getText()         Returns the current record's "text" value
 * @method Comments  setCid()          Sets the current record's "cid" value
 * @method Comments  setPid()          Sets the current record's "pid" value
 * @method Comments  setCreated()      Sets the current record's "created" value
 * @method Comments  setSubjectName()  Sets the current record's "subject_name" value
 * @method Comments  setSubjectId()    Sets the current record's "subject_id" value
 * @method Comments  setText()         Sets the current record's "text" value
 * 
 * @package    pd
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComments extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comments');
        $this->hasColumn('cid', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('pid', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('created', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('subject_name', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('subject_id', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('text', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}