<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Tags', 'doctrine');

/**
 * BaseTags
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $tid
 * @property integer $pid
 * @property timestamp $created
 * @property string $subject_id
 * @property string $subject_name
 * @property string $xcoord
 * @property string $ycoord
 * 
 * @method integer   getTid()          Returns the current record's "tid" value
 * @method integer   getPid()          Returns the current record's "pid" value
 * @method timestamp getCreated()      Returns the current record's "created" value
 * @method string    getSubjectId()    Returns the current record's "subject_id" value
 * @method string    getSubjectName()  Returns the current record's "subject_name" value
 * @method string    getXcoord()       Returns the current record's "xcoord" value
 * @method string    getYcoord()       Returns the current record's "ycoord" value
 * @method Tags      setTid()          Sets the current record's "tid" value
 * @method Tags      setPid()          Sets the current record's "pid" value
 * @method Tags      setCreated()      Sets the current record's "created" value
 * @method Tags      setSubjectId()    Sets the current record's "subject_id" value
 * @method Tags      setSubjectName()  Sets the current record's "subject_name" value
 * @method Tags      setXcoord()       Sets the current record's "xcoord" value
 * @method Tags      setYcoord()       Sets the current record's "ycoord" value
 * 
 * @package    pd
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTags extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tags');
        $this->hasColumn('tid', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('pid', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('created', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('subject_id', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('subject_name', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('xcoord', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('ycoord', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}