<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/08/18 17:00:36

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=photodump',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
